// * Set Actions
export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_PROVIDER_STATUS = 'SET_PROVIDER_STATUS';

// * Load actions
export const LOAD_CONTRACT_INTO_LIBRARY_REQUEST =
  'LOAD_CONTRACT_INTO_LIBRARY_REQUEST';

// * Init actions
export const INIT_CONTRACT_REQUEST = 'INIT_CONTRACT_REQUEST';
// ! NOTE: No reducer associated with action
export const INIT_CONTRACT_FROM_LIBRARY_REQUEST =
  'INIT_CONTRACT_FROM_LIBRARY_REQUEST';

// * Deploy actions
export const DEPLOY_CONTRACT_REQUEST = 'DEPLOY_CONTRACT_REQUEST';
export const DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST =
  'DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST';

// * Sign actions
export const SIGN_TYPED_MESSAGE_REQUEST = 'SIGN_TYPED_MESSAGE_REQUEST';
export const SIGN_MESSAGE_REQUEST = 'SIGN_MESSAGE_REQUEST';
// ! NOTE: No reducer associated with action
export const SIGN_TRANSACTION_REQUEST = 'SIGN_TRANSACTION_REQUEST';
